using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace QLSV
{
    public partial class FormMonHoc : DevExpress.XtraEditors.XtraForm
    {
        public FormMonHoc()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            sinhvienTableAdapter1.Fill(qldsvDataSet1.SINHVIEN);
            // This line of code is generated by Data Source Configuration Wizard
            monhocTableAdapter1.Fill(qldsvDataSet2.MONHOC);
            // This line of code is generated by Data Source Configuration Wizard
            monhocTableAdapter2.Fill(qldsvDataSet3.MONHOC);
            // This line of code is generated by Data Source Configuration Wizard
            monhocTableAdapter3.Fill(qldsvDataSet4.MONHOC);
        }

        private void quitFormBtn_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void viewDanhSachMon_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            if(viewDanhSachMon.SelectedRowsCount > 0)
            {
                maMon.Text = viewDanhSachMon.GetFocusedDataRow()["MAMH"].ToString();
                tenMon.Text = viewDanhSachMon.GetFocusedDataRow()["TENMH"].ToString();
            }
        }

        private void adjustBtn_Click(object sender, EventArgs e)
        {
            danhSachMon.Enabled = false;
            groupEdit.Enabled = true;
        }

        private void exitBtn_Click(object sender, EventArgs e)
        {
            //xóa trạng thái

            danhSachMon.Enabled = true;
            groupEdit.Enabled = false;
        }
    }
}