USE [master]
GO

/****** Object:  Database [QLDSV]    Script Date: 11/26/2020 6:56:26 PM ******/
CREATE DATABASE [QLDSV]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLDSV', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\QLDSV.mdf' , SIZE = 23552KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'QLDSV_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\QLDSV_log.ldf' , SIZE = 29504KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [QLDSV] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLDSV].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLDSV] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLDSV] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLDSV] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLDSV] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLDSV] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLDSV] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QLDSV] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLDSV] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLDSV] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLDSV] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLDSV] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLDSV] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLDSV] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLDSV] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLDSV] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QLDSV] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLDSV] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLDSV] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLDSV] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLDSV] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLDSV] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLDSV] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLDSV] SET RECOVERY FULL 
GO

ALTER DATABASE [QLDSV] SET  MULTI_USER 
GO

ALTER DATABASE [QLDSV] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLDSV] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLDSV] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLDSV] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [QLDSV] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLDSV] SET  READ_WRITE 
GO

